# blight
# Autogenerated from man page /usr/share/man/man1/blight.1.gz
complete -c blight -s h -l help -d 'Show help message and quit'
complete -c blight -s d -l device -d 'Specify which device to act on.  If not specified, chooses a sane'

