# ctpl
# Autogenerated from man page /usr/share/man/man1/ctpl.1.gz
complete -c ctpl -s h -l help -d 'Prints the command line options'
complete -c ctpl -s o -l output -d 'Write output to FILE.  If not provided, defaults to stdout'
complete -c ctpl -s e -l env-file -d 'Add environment from ENVFILE.  This option may appear more than once'
complete -c ctpl -s c -l env-chunk -d 'Add environment chunk CHUNK.  This option may appear more than once'
complete -c ctpl -s v -l verbose -d 'Be verbose'
complete -c ctpl -l version -d 'Print the version information and exit'
complete -c ctpl -l encoding -d 'Specify the encoding of the input and output files'

