# nethogs
# Autogenerated from man page /usr/share/man/man8/nethogs.8.gz
complete -c nethogs -s h -d 'display available commands usage'
complete -c nethogs -s V -d 'print version info'
complete -c nethogs -s d -d 'delay for refresh rate'
complete -c nethogs -s v -d 'select view mode'
complete -c nethogs -s p -d 'sniff in promiscuous mode (not recommended)'
complete -c nethogs -s a -d 'monitor all devices, even loopback/stopped ones'
complete -c nethogs -s t -d tracemode
complete -c nethogs -s c -d 'limit number of refreshes'
complete -c nethogs -s s -d 'sort by traffic sent'
complete -c nethogs -s l -d 'display command line'

