# pyroom
# Autogenerated from man page /usr/share/man/man1/pyroom.1.gz
complete -c pyroom -l help -d 'Prints the command line options and exits'
complete -c pyroom -l version -d 'Prints the programm\'s version and exits'

